from controlevendas.serializers.ProdutoSerializers import ProdutoSerializers
from controlevendas.serializers.PedidoSerializers import PedidoSerializers
from controlevendas.serializers.RelatorioSerializers import RelatorioSerializers
