# Generated by Django 3.2.5 on 2021-07-11 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('dataNascimento', models.DateField(verbose_name='Data de nascimento')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['dataCadastro'],
            },
        ),
        migrations.CreateModel(
            name='LoteFabricacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Indentificação do lote')),
                ('dataFabricacao', models.DateField(verbose_name='Data de fabricação')),
                ('quantidadeProduto', models.IntegerField(default=0, verbose_name='Quantidade de produtos')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
            ],
            options={
                'verbose_name': 'Lote de Fabricação',
                'verbose_name_plural': 'Lotes de Fabricação',
                'ordering': ['dataCadastro'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Indentificação do produto')),
                ('Nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Valor do produto')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
                ('numeroLote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlevendas.lotefabricacao', verbose_name='Lote de fabricação do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['dataCadastro'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('dataNascimento', models.DateField(verbose_name='Data de nascimento')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['dataCadastro'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoQuantidadePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeProduto', models.IntegerField(default=0, verbose_name='Quantidade de produtos para pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlevendas.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Quantidade',
                'verbose_name_plural': 'Quantidades',
                'ordering': ['quantidadeProduto'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPedido', models.IntegerField(verbose_name='Número do pedido')),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor total do Pedido')),
                ('dataCompra', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlevendas.cliente', verbose_name='Cliente')),
                ('produtos', models.ManyToManyField(to='controlevendas.ProdutoQuantidadePedido', verbose_name='Produto com a quantidade')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlevendas.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['dataCompra'],
            },
        ),
    ]
